#!/usr/bin/perl

use Dateutil;
$eday = $ARGV[0];

$cday = Dateutil::e2d($eday);

($month, $day, $year) = split("/", $cday);

$newcday = "$month/1/$year";

$newjday = Dateutil::d2jf($newcday);
print("$newjday\n");
