#!/usr/bin/perl
# 
# Program j2d transforms the date from a calendar day to a year day and
# vice versa.
#
# Calling sequence is: j2d 98309 to get the calendar day and
# j2d 11/05/98 to get the year day.
#
# Taken from the Cwutil.pm package and modified on 07/16/98 by EAH

$opt_s = 0;
$opt_l = 0;
$opt_m = 0;
$opt_h = 0;

use Getopt::Std;

getopts('shlm');

@months = (31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31);

$jdate = $ARGV[0];

# looks for string in the form 98309 here...
if (($yr, $jday) = ($jdate =~ /^(\d\d)(\d*)$/)) {
     ($yr < 50) ? ($yr += 2000) : ($yr += 1900);
     $months[1] = 29 if (($yr % 4 == 0) || ($yr % 400 == 0));
     for ($i = 0; $i < 12; $i++) {
          if ($jday <= $months[$i]) {
               $day = $jday;
               $mo = $i;
               last;
          }			
     $jday -= $months[$i];
     }
     $mo++;
     #$ans = sprintf "%02d\/%02d\/%04d", $mo, $day, $yr;		
     if ($opt_s eq 1) {
        if ($opt_l eq 1) {
           $ans = sprintf "%d\/%d\/%04d", $mo, $day, $yr;		
        } else {
           $ans = sprintf "%d\/%d\/%02d", $mo, $day, substr($yr, 2, 2);		
        }
        print("$ans");
     } elsif ($opt_m eq 1) {
        $syr = substr($yr, 2, 2);
        print("$mo  $syr");
     } else {
        $ans = sprintf "%d\/%d\/%d", $mo, $day, $yr;		
        print("The Year day is: $ans\n");
     }
     #$ans = sprintf "%d\/%d\/%d", $mo, $day, substr($yr, 2, 2);		
     #print("The date is: $ans\n");
     #print("$ans\n");
}
# looks for string in the form 11/05/98 here...
#elsif (($mo, $day, $yr) = ($jdate=~ /^(\d?\d)\/(\d?\d)\/(\d?\d)$/)) {
elsif (($mo, $day, $yr) = ($jdate=~ /^(\d?\d)\/(\d?\d)\/(\d+)$/)) {
     if ($yr < 100) {
        ($yr < 50) ? ($yr += 2000) : ($yr += 1900);
      }
     $months[1] = 29 if (($yr % 4 == 0) || ($yr % 400 == 0));
     $jday = 0;
     for ($i = 0; $i < $mo - 1; $i++) {
          $jday += $months[$i];
     }
     $jday += $day;
     #if ($yr > 1000) {
     #   $syear = substr($yr, 2, 2);
     #} else {
     #   $syear = $yr;
     #   $fullans = sprintf "%02d%03d", $yr, $jday;
     #}
     $syear = substr($yr, 2, 2);
     $fullans = sprintf "%04d%03d", $yr, $jday;
     $shortans = sprintf "%02d%03d", $syear, $jday;
     $halfans = sprintf "%03d", $jday;
     if ($opt_s eq 1) {
        if ($opt_h eq 1) {
           print("$halfans");
        } elsif ($opt_l eq 1) {
           print("$fullans");
        } else {
           print("$shortans");
        }
     } else {
        print("The year day is: $fullans\n");
     }
}
